services:
  dbcsv-server:
    image: databaseengine
    build:
      context: .
      dockerfile: ./dbcsv/engine/Dockerfile
    ports:
      - 80:80

  dbcsv-client:
    image: dbapi2
    build:
      context: .
      dockerfile: ./dbcsv/dbapi2/Dockerfile
